# <center style="font-family: consolas; font-size: 32px; font-weight: bold;">张量 Tensor</center>
<p><center style="color:#949494; font-family: consolas; font-size: 20px;"></center></p>

***

# <center style="font-family: consolas; font-size: 32px; font-weight: bold;"></center>

<font face='consolas' size=3 color=#f8000b>1. Conception and Expression</font>

In [2]:
# Tensor
import torch

print(torch.__version__)

2.4.1


In [8]:
tensor = torch.tensor([1, 2, 3])

print(tensor.shape)
print(tensor)

torch.Size([3])
tensor([1, 2, 3])


In [14]:
zero_tensor = torch.zeros(2, 3)
print(zero_tensor)

rand_tensor = torch.rand(3, 3)
print(rand_tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.6702, 0.8677, 0.6568],
        [0.6150, 0.1562, 0.7362],
        [0.7129, 0.6304, 0.1730]])


In [ ]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# sum
result = tensor1 + tensor2
print(result)  # output: tensor([5, 7, 9])

# multiple
result = tensor1 * tensor2
print(result)  # output: tensor([4, 10, 18])
